include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  strong-mode:
    implicit-dynamic: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/dependencies.config.dart"
  errors:
    invalid_annotation_target: ignore
