name: cupertino_store
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  go_router: ^3.0.7
  intl: ^0.17.0
  shrine_images: ^2.0.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  very_good_analysis: ^2.4.0

flutter:
  generate: true
